### ISSUE TITLE
does the program support phoenixgo weight now

### ISSUE THREAD

**Issue by l1t1** [new3Rs/a_master_of_go#74]
i saw a picture of apple app store said that

**Comment by l1t1** [comment]
its true, but the Chinese translation is poor
它是一个Go AI，具有强大的开源AI神经网络。
go-围棋
你可以在学习时将它作为一个强大的对手和好老师。

使用新iPad Pro的A12X仿生处理器和ELF OpenGo权量v1，播出每秒执行170次以上，而iPhone XS / XR的A12仿生处理器则超过每秒150次！ 两者都超过笔记本电脑，可与台式电脑相媲美。

有关您的信息，iPad Pro 9.7英寸型号((A9X处理器))的播放速度约为每秒10次，iPhone 6((A8处理器))的播放速度约为每秒1次。我认为大多数业余爱好者比这更强大，但在考虑购买时请小心。
小心-注意 播放-下棋
好好享受！

（对不起机器翻译的不良陈述）
新内容
版本记录
2019年3月12日 版本 2.2.0
此版本添加了新的神经网络和即时参数设置，并修改了几个问题。

1.添加了腾讯PhoenixGo网络。
2.添加了即时参数设置功能，以将引擎参数与着名的AI匹配。
3.即使播出次数很少，也将“随机开放”随机化。
4.修改了在残疾人游戏中辞职的条件。
残疾人-让子棋 辞职-认输
5.修改了“钦佩”的条件。
6.当有许多宝石时，提高了播出速度。
宝石-棋子
7.修正了AI首次播放时没有延长读数的错误。
8.修改了滚动部分的UI。

https://itunes.apple.com/cn/app/%E5%9B%B4%E6%A3%8B%E8%80%81%E5%B8%88/id1442035374?ign-mpt=uo%3D4&mt=8

**Comment by y-ich** [comment]
@l1t1 san,

Yes, now the app supports PhoenixGo v1 weight.

Sorry for poor translation.
Since I have no ability to check it, I put Google translation from English statement without any modifications^^;

**Comment by l1t1** [comment]
please post theEnglish version, may i help to check it?

**Comment by y-ich** [comment]
Wow, thank you, @l1t1 san!
I am glad to hear from you, but I may hesitate to ask one-time help since the app continues to be updated...

Anyway, here are statements of English version.

- Introduction

It is a Go AI featuring a neural network of that strong, open source AI.

You can use it as a strong opponent and as a good teacher at the time of study.

With A12X Bionic processor of new iPad Pro, the playouts are performed over 170 times per second with ELF OpenGo weight v1, and with A12 Bionic processor of iPhone XS/XR, over 150 times per second! Both exceed notebook computers and is comparable to desktop computers.

For your information, the playout speed on the iPad Pro 9.7 inch model(A9X processor) will be about 10 times per second, and the one on the iPhone 6(A8 processor) will be about 1 time per second. I think that even so it is stronger than most amateurs, but I am sorry that patterns of misreading ladders will increase.
Please be careful when considering purchasing.

Enjoy it!

- Relase note

This version adds a new neural network and an instant parameter setting, and modifies several issues.
1. Added the Tencent PhoenixGo network.
2. Added Instant Parameter Setting functionality to match engine parameters to famous AIs.
3. Made "Stochastic Opening" stochastic even when the number of playouts was small.
4. Modified the condition to resign at handicapped game.
5. Modified the condition for “admiration”.
6. Improved playout speed when there are many stones.
7. Fixed a bug that did not extend the reading when the AI ​​plays first.
8. Modified the UI of the scroll parts.

**Comment by l1t1** [comment]
围棋老师介绍

它是一个围棋 AI，具有强大的开源AI神经网络。

你可以在学习时将它作为一个强大的对手和好老师。

使用新款iPad Pro的A12X 仿生处理器，模拟速度为每秒170次，使用ELF OpenGo v1权重，而采用iPhone XS / XR的A12仿生处理器，模拟速度超过每秒150次！两者都超过笔记本电脑，可与台式电脑相媲美。

提示您一下，iPad Pro 9.7英寸型号（A9X处理器）的播放速度大约是每秒10次，iPhone 6（A8处理器）的模拟速度大约是每秒1次。 我认为即便如此，它也比大多数业余爱好者强，但我很抱歉，这时会增加算错征子的情况。
在考虑购买时请注意。

好好享用！

     相关说明

此版本添加了新的神经网络和即时参数设置，并修改了几个问题。

     添加了腾讯PhoenixGo权重。
     添加了即时参数设置功能，以将引擎参数与著名的AI相一致。
     即使模拟次数很少，“随机开局”也是随机的。
     修改了在让子棋对局中认输的条件。
     修改了“钦佩”的条件。--- unknown
     提高了在棋子很多时的模拟速度。
     修复了AI首次模拟时没有延长读数的错误。--- unknown
     修改了滚动部分的UI。

**Comment by l1t1** [comment]
（A9X处理器）的播放 ->（A9X处理器）的模拟

**Comment by y-ich** [comment]
@l1t1 san, thank you!

I will replace the introduction to your translation in the next version.
About release note..., maybe I will use Google translation again^^;

**Comment by ChinChangYang** [comment]
@y-ich The translation looks good, but I am not sure what the following sentence means in the release note:

Modified the condition for “admiration”.

Do you have Japanese version of the sentence or could you please explain the condition of admiration?

Thanks.

**Comment by y-ich** [comment]
@ChinChangYang san, 

"admiration" is a function which was added in the previous version.
In the study mode, when the winrate of the move exceeds the one of AI's best move, AI displays the move number as admiration(❗).
'Modified the condition for “admiration”' means that I changed the threshold of difference between winrates. (It was 5% in the previous version and now it is 2%)

**Comment by y-ich** [comment]
@l1t1 san,

I released version 2.2.1 today. The overview in Chinese is now your translation.
Thank you for your cooperation!

**Comment by l1t1** [comment]
I see, but i thought you can use an editor to replace all known wrong Chinese words in google result with that in my result, such as殘疾人-让子棋, or try use google to translate from Japanese?

**Comment by y-ich** [comment]
@l1t1 san,

I have another service which translates Chinese Go news to Japanese, and adopted the method you suggest, with other translation service (not Google).
It works so-so well.
But it (replacing words) did not work well basically for Google translation since it is powered by neural network.
So I totally gave up to improve translation since then^^;
